#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Increase memory limit for Node.js
export NODE_OPTIONS="--max-old-space-size=4096"

# Run lint-staged for formatting and linting
yarn lint-staged

# Run type checking
yarn tsc --noEmit
